# Generated by Django 4.0.6 on 2022-08-17 22:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_post_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='to_follow',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
