# Generated by Django 4.0.6 on 2022-08-17 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_user_to_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='to_follow',
            new_name='following',
        ),
    ]
