# Generated by Django 4.0.6 on 2022-09-10 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_post_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last_updated',
        ),
    ]
